### ISSUE TITLE
Report node improvements

### ISSUE THREAD

**Issue by ric394** [APSIMInitiative/ApsimX#8356]
### Describe the new feature

# Task list

- [x] Make the descriptions verbose to improve recognition (no module names)
- [x] Standardize descriptions
- [x] Filtering on description needs to make sure that nothing appears from out of scope.
- [x] Peer check correctness of common variables and common events
- [x] Check the units of variables
- [x] Remove 'layered' from descriptions
- [x] Add the type to list types
- [x] Add a field that has the module name (Wheat, Sugarcane etc)
- [x] Add a column for the module names
- [x] Change ReportView to show new 'Node' column.
- [x] Make ReportVariables which Node type is an interface show up when all other scoped ReportVariables are shown.
- [x] Need to make sure that models that implement an interface are included in filtering as some variables/events are linked to an interface.
   - [x] Make a function that finds model names that implement a specific interface.
   - [x] Make sure fetching common report variables and events takes these into account when filtering.
       - [x] report variables text change event now implements
       - [x] report events text change event now implements
- [x] Make it so that when a plant variable is double-clicked or dragged, a line is added for each plant type is in the simulation.
    - [x] A line is added for each plant when double-clicked.
    - [x] A line is added for each plant when a plant variable is dragged.

**Comment by ric394** [comment]
# Bugs to resolve

- [ ] Have the splitters on panes actually stay where they are when set in the Report node.
- [ ] Deleting lines in the report variables list and then double-clicking causes an exception
- [ ] double-clicking a report variable causes the node column's value to appear in the report variables list rather than the code value.
