### ISSUE TITLE
Command line feature docs improvements/additions

### ISSUE THREAD

**Issue by ric394** [APSIMInitiative/ApsimX#8368]
### Describe the new feature

Requests for higher quality information on the command line feature have been received. To help with this, more in-depth documentation/tutorials should be created to enable users to follow self-guided documents to better understand it's usage.

# Tasks
- [x] Create a tutorial on how to build up a simulation from scratch from the command line.
- [x] Create several tutorials that explain how to create APSIM files for specific scenarios.
    - [x] Changing weather files
    - [x] Changing soils
- [x] Show how to do repeated changes
    - [x] From within config file
    - [x] Using batch/bash files
- [x] Create a linux version as this will be the more common platform for its usage.
