### ISSUE TITLE
Observed Input and Report

### ISSUE THREAD

**Issue by par456** [APSIMInitiative/ApsimX#8462]
### Describe the new feature

At the moment we have ExcelInput to read in observed files, Report to gather predicted values from simulations and PredictedObserved to match up those data tables at the end of the simulation. However, this often leads to reports that gather a lot more variables than what is required to match the observed data, and mistakes when matching up the observed and predicted columns.

To address this, we are working on a new PredictedObserved system that can read in an observed file, generate the required reports for matching data and output the predicted observed tables with less manual setup than currently required. We'll be working on this in parts.

**Part 1**
- [ ] An ObservedInput model that replicates the functionality of ExcelInput, but also reads all the column headings out of the file and makes them available
- [ ] An ObservedReport that acts like a report, but builds the list of reporting variables from the columns ObeservedInput read in
- [ ] ObservedReport needs to be able to take a frequency to report on so that it can replace existing reports
- [ ] The column names are filtered based on the observed values that the simulation has
- [ ] ObservedReport has a matching column name that can be used to filter the rows that are used for filtering column names

**Part 2**
- [ ] DailyReport is used for both observed data and graphing "predicted only" data, so ObservedInput needs to gather all the variables required for graphs
- [ ] A way to add new variables to the ObservedInput so they can be selected for graphs
- [ ] ObservedReport needs to have filtering options
- [ ] ObservedReport needs to allow or not the graphing variables for columns

**Part 3**
- [ ] ObservedReport should replace the functionality of PredictedObserved and return a table with predicted and observed columns
- [ ] Tests must be adjusted to now work on ObservedInput/ObservedReport instead of PredictedObserved

**Part 4**
- [ ] Create a flag or marker for running on Jenkins so that all data not required for doing predicted observed stats is not gathered. Such as daily values for graphing that don't have an observed value.
- [ ] Don't run any other reports while this flag is active so that less data must be recorded
- [ ] Looking to gain about 20% back on Jenkins validation speed.

**Comment by par456** [comment]
Ignore that link, quoted wrong issue number on that PR

**Comment by HamishBrownPFR** [comment]
@par456 Highlighting a couple of issues in the wheat test set that I assume you have in scope for this but wanting to make sure.
1.  We have a manager script called LocationInfo in all simulations in the wheat test that contains indexing data, Country, State and Region.  We also have a SowingReport in all simulations that outputs the LocationInfo variables along with Longitute, Lattitude and Cultivar which are output at sowing to provide indexing info for data analysis.  These elements need to be added to each simulation manually.  If I recall correctly @byzheng used a script to populate the LocationInfo properties based on Lat and Long.  It would be more user friendly and less error prone if the system just worked this index info out in the background and included it in report files rather than needing report them manually and joint them back to the other reported data later.
2. We have a manager that calculates NDVI in SOME simulations and include a Report to output its values in the associated simulations.  This is needed because currently the report throws an error for simulations where the NDVI script is not present if we try to report NDVI for all simulations.  This is annoying because we have to find the simulations where we have observed NDVI data and include elements needed to provide a predicted value.  It also means this data comes in a separate table which makes subsequent data management fiddly.

**Comment by byzheng** [comment]
@HamishBrownPFR  I agree with your point. It would be much useful to export met information into report (might be in a separate table).

These information are really helpful to externally process outputs by other program languages (e.g. wheat validation file).
